require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SanitationsController do

  # This should return the minimal set of attributes required to create a valid
  # Sanitation. As you add validations to Sanitation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "start_date" => "2013-03-19" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SanitationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sanitations as @sanitations" do
      sanitation = Sanitation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sanitations).should eq([sanitation])
    end
  end

  describe "GET show" do
    it "assigns the requested sanitation as @sanitation" do
      sanitation = Sanitation.create! valid_attributes
      get :show, {:id => sanitation.to_param}, valid_session
      assigns(:sanitation).should eq(sanitation)
    end
  end

  describe "GET new" do
    it "assigns a new sanitation as @sanitation" do
      get :new, {}, valid_session
      assigns(:sanitation).should be_a_new(Sanitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested sanitation as @sanitation" do
      sanitation = Sanitation.create! valid_attributes
      get :edit, {:id => sanitation.to_param}, valid_session
      assigns(:sanitation).should eq(sanitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sanitation" do
        expect {
          post :create, {:sanitation => valid_attributes}, valid_session
        }.to change(Sanitation, :count).by(1)
      end

      it "assigns a newly created sanitation as @sanitation" do
        post :create, {:sanitation => valid_attributes}, valid_session
        assigns(:sanitation).should be_a(Sanitation)
        assigns(:sanitation).should be_persisted
      end

      it "redirects to the created sanitation" do
        post :create, {:sanitation => valid_attributes}, valid_session
        response.should redirect_to(Sanitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sanitation as @sanitation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sanitation.any_instance.stub(:save).and_return(false)
        post :create, {:sanitation => { "start_date" => "invalid value" }}, valid_session
        assigns(:sanitation).should be_a_new(Sanitation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sanitation.any_instance.stub(:save).and_return(false)
        post :create, {:sanitation => { "start_date" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sanitation" do
        sanitation = Sanitation.create! valid_attributes
        # Assuming there are no other sanitations in the database, this
        # specifies that the Sanitation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sanitation.any_instance.should_receive(:update_attributes).with({ "start_date" => "2013-03-19" })
        put :update, {:id => sanitation.to_param, :sanitation => { "start_date" => "2013-03-19" }}, valid_session
      end

      it "assigns the requested sanitation as @sanitation" do
        sanitation = Sanitation.create! valid_attributes
        put :update, {:id => sanitation.to_param, :sanitation => valid_attributes}, valid_session
        assigns(:sanitation).should eq(sanitation)
      end

      it "redirects to the sanitation" do
        sanitation = Sanitation.create! valid_attributes
        put :update, {:id => sanitation.to_param, :sanitation => valid_attributes}, valid_session
        response.should redirect_to(sanitation)
      end
    end

    describe "with invalid params" do
      it "assigns the sanitation as @sanitation" do
        sanitation = Sanitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sanitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => sanitation.to_param, :sanitation => { "start_date" => "invalid value" }}, valid_session
        assigns(:sanitation).should eq(sanitation)
      end

      it "re-renders the 'edit' template" do
        sanitation = Sanitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sanitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => sanitation.to_param, :sanitation => { "start_date" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sanitation" do
      sanitation = Sanitation.create! valid_attributes
      expect {
        delete :destroy, {:id => sanitation.to_param}, valid_session
      }.to change(Sanitation, :count).by(-1)
    end

    it "redirects to the sanitations list" do
      sanitation = Sanitation.create! valid_attributes
      delete :destroy, {:id => sanitation.to_param}, valid_session
      response.should redirect_to(sanitations_url)
    end
  end

end
